# Generated by Django 5.2 on 2025-08-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('pedagogico', '__first__'),
        ('professor', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='emprestimomaterial',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedagogico.aluno'),
        ),
        migrations.RemoveField(
            model_name='falta',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='suspensao',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='falta',
            name='disciplina',
        ),
        migrations.AlterField(
            model_name='emprestimomaterial',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.colaborador'),
        ),
        migrations.AlterField(
            model_name='eventoextracurricular',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='pedagogico.aluno'),
        ),
        migrations.DeleteModel(
            name='Advertencia',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Mensalidade',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Suspensao',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
        migrations.DeleteModel(
            name='Presenca',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Falta',
        ),
    ]
