# Generated by Django 5.1.8 on 2025-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('ti', 'Tecnologia da Informação'), ('aluno', 'Aluno'), ('professor', 'Professor'), ('coordenacao', 'Coordenação'), ('secretaria', 'Secretaria'), ('diretor', 'Diretor'), ('responsavel', 'Responsável')], default='aluno', max_length=20),
        ),
    ]
