# Generated by Django 5.2.5 on 2025-10-29 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_aluno_disciplina_alter_usuario_cargo_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas', to='base.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.disciplina')),
                ('professor', models.ForeignKey(limit_choices_to={'cargo': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['ano', 'nome'],
            },
        ),
    ]
