# Generated by Django 5.2.5 on 2025-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno'), ('administrador', 'Administrador'), ('coordenador', 'Coordenador'), ('diretor', 'Diretor'), ('ti', 'TI')], max_length=50),
        ),
    ]
