# Generated by Django 5.2.6 on 2025-11-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogico', '0002_aluno_status_eventoacademico_notificacao_responsavel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventoExtracurricular',
        ),
    ]
